name = "AFTERLIGHT"
author = "Shane + ECHO"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b814b7f0ee305fa9f0dfb764ba2057eb19f44269ca538cd85468426e99ee6f3e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
