name = "AFTERLIGHT"
author = "Shane + ECHO"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d13c1ec90d21d3e75e4f176bcb9ebcc78e27fa1d04d5f1a72e0dfa61167ac19"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
