name = "AFTERLIGHT"
author = "Shane + ECHO"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a5fc2cfd7102ede80a6b7c59da73e39008d6b3d8fe1d822e515e4dce2b64710"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
