// Generated by tools/build-quests.py. Do not edit by hand.
const AFTERLIGHT_QUEST_ITEM_AUDIT_DIGEST = '9afe160c41ff9d5d9e1c4b1ddf97171b837369ad74648726fc5d6fc7f55d4579'
const AFTERLIGHT_QUEST_ITEM_IDS = [
  "ars_nouveau:enchanting_apparatus",
  "ars_nouveau:imbuement_chamber",
  "ars_nouveau:novice_spell_book",
  "ars_nouveau:source_gem",
  "ars_nouveau:worn_notebook",
  "create:andesite_alloy",
  "create:brass_ingot",
  "create:goggles",
  "create:iron_sheet",
  "create:mechanical_press",
  "create:shaft",
  "create:water_wheel",
  "create:wrench",
  "functionalstorage:oak_1",
  "immersiveengineering:coke_oven",
  "immersiveengineering:ingot_steel",
  "immersiveengineering:workbench",
  "kubejs:requisition_chit",
  "mekanism:alloy_infused",
  "mekanism:basic_universal_cable",
  "mekanism:energized_smelter",
  "mekanism:enrichment_chamber",
  "mekanism:ingot_osmium",
  "mekanism:metallurgic_infuser",
  "mekanism:steel_casing",
  "mekanismgenerators:heat_generator",
  "minecraft:blast_furnace",
  "minecraft:bread",
  "minecraft:chiseled_tuff_bricks",
  "minecraft:crafting_table",
  "minecraft:diamond",
  "minecraft:enchanted_golden_apple",
  "minecraft:experience_bottle",
  "minecraft:golden_apple",
  "minecraft:iron_block",
  "minecraft:iron_ingot",
  "minecraft:netherite_scrap",
  "minecraft:netherrack",
  "minecraft:oak_planks",
  "minecraft:recovery_compass",
  "minecraft:red_bed",
  "minecraft:redstone",
  "minecraft:redstone_block",
  "minecraft:stone_pickaxe",
  "minecraft:torch",
  "modern_industrialization:bronze_boiler",
  "modern_industrialization:bronze_ingot",
  "modern_industrialization:bronze_machine_casing",
  "modern_industrialization:forge_hammer",
  "modern_industrialization:steam_mining_drill",
  "sophisticatedbackpacks:backpack"
]

ServerEvents.loaded(() => {
  const bootNonce = '__AFTERLIGHT_BOOT_NONCE__'
  const invalid = AFTERLIGHT_QUEST_ITEM_IDS.filter(id => !Item.exists(id))
  if (invalid.length > 0) {
    invalid.forEach(id => console.error(`[AFTERLIGHT QUEST ITEM AUDIT] INVALID ${id}`))
    console.error(`[AFTERLIGHT QUEST ITEM AUDIT] FAILED ${AFTERLIGHT_QUEST_ITEM_AUDIT_DIGEST} ${bootNonce}`)
    return
  }
  console.info(`[AFTERLIGHT QUEST ITEM AUDIT] OK ${AFTERLIGHT_QUEST_ITEM_AUDIT_DIGEST} ${AFTERLIGHT_QUEST_ITEM_IDS.length} ${bootNonce}`)
})
