// Generated by tools/build-quests.py. Do not edit by hand.
const AFTERLIGHT_QUEST_ITEM_AUDIT_DIGEST = '5fc8ec0db1298622c464333c797490c91612969e1afbe4f5cb38022c2f0365ad'
const AFTERLIGHT_QUEST_COMMODITY_FIXTURE_SHA256 = '52ca9efb512a97827c25494fb4070287709c50f968547b6a1d0d33f2d855af27'
const AFTERLIGHT_QUEST_ITEM_IDS = [
  "ae2:1k_crafting_storage",
  "ae2:256k_crafting_storage",
  "ae2:4k_crafting_storage",
  "ae2:blank_pattern",
  "ae2:calculation_processor",
  "ae2:calculation_processor_press",
  "ae2:cell_component_256k",
  "ae2:certus_quartz_crystal",
  "ae2:charged_certus_quartz_crystal",
  "ae2:charger",
  "ae2:controller",
  "ae2:crafting_monitor",
  "ae2:crafting_pattern",
  "ae2:crafting_terminal",
  "ae2:creative_energy_cell",
  "ae2:drive",
  "ae2:energy_acceptor",
  "ae2:engineering_processor_press",
  "ae2:fluix_crystal",
  "ae2:fluix_glass_cable",
  "ae2:guide",
  "ae2:inscriber",
  "ae2:interface",
  "ae2:item_storage_cell_1k",
  "ae2:item_storage_cell_256k",
  "ae2:level_emitter",
  "ae2:logic_processor",
  "ae2:logic_processor_press",
  "ae2:meteorite_compass",
  "ae2:molecular_assembler",
  "ae2:pattern_encoding_terminal",
  "ae2:pattern_provider",
  "ae2:quantum_entangled_singularity",
  "ae2:quantum_link",
  "ae2:quantum_ring",
  "ae2:quartz_glass",
  "ae2:silicon_press",
  "ae2:storage_bus",
  "afterlight:echo",
  "ars_nouveau:arcane_pedestal",
  "ars_nouveau:enchanting_apparatus",
  "ars_nouveau:imbuement_chamber",
  "ars_nouveau:novice_spell_book",
  "ars_nouveau:ritual_brazier",
  "ars_nouveau:source_gem",
  "ars_nouveau:source_jar",
  "ars_nouveau:worn_notebook",
  "cataclysm:ancient_metal_ingot",
  "cataclysm:mechanical_fusion_anvil",
  "create:andesite_alloy",
  "create:andesite_funnel",
  "create:belt_connector",
  "create:blaze_burner",
  "create:brass_funnel",
  "create:brass_ingot",
  "create:cogwheel",
  "create:creative_motor",
  "create:crushing_wheel",
  "create:deployer",
  "create:goggles",
  "create:iron_sheet",
  "create:mechanical_arm",
  "create:mechanical_crafter",
  "create:mechanical_press",
  "create:millstone",
  "create:portable_storage_interface",
  "create:precision_mechanism",
  "create:railway_casing",
  "create:schedule",
  "create:shaft",
  "create:track",
  "create:water_wheel",
  "create:wrench",
  "draconicevolution:chaotic_core",
  "draconicevolution:dislocator",
  "draconicevolution:draconium_core",
  "draconicevolution:module_core",
  "enderio:basic_capacitor_bank",
  "enderio:conduit",
  "eternal_starlight:starlight_silver_coin",
  "fluxnetworks:flux_controller",
  "fluxnetworks:flux_plug",
  "fluxnetworks:flux_point",
  "ftbfiltersystem:smart_filter",
  "functionalstorage:oak_1",
  "functionalstorage:storage_controller",
  "functionalstorage:void_upgrade",
  "immersiveengineering:assembler",
  "immersiveengineering:capacitor_creative",
  "immersiveengineering:capacitor_lv",
  "immersiveengineering:component_electronic_adv",
  "immersiveengineering:connector_lv",
  "immersiveengineering:conveyor_basic",
  "immersiveengineering:creosote_bucket",
  "immersiveengineering:hammer",
  "immersiveengineering:heavy_engineering",
  "immersiveengineering:ingot_steel",
  "immersiveengineering:manual",
  "immersiveengineering:treated_wood_horizontal",
  "immersiveengineering:wirecoil_copper",
  "immersiveengineering:workbench",
  "irons_spellbooks:alchemist_cauldron",
  "irons_spellbooks:arcane_anvil",
  "irons_spellbooks:arcane_essence",
  "irons_spellbooks:copper_spell_book",
  "irons_spellbooks:inscription_table",
  "irons_spellbooks:scroll_forge",
  "kubejs:ascendancy_seal",
  "kubejs:deep_vault_key",
  "kubejs:gate_blueprint",
  "kubejs:gate_industrial_anchor",
  "kubejs:gate_isotopic_core",
  "kubejs:gate_kinetic_frame",
  "kubejs:gate_lattice_matrix",
  "kubejs:gate_of_return_core",
  "kubejs:requisition_chit",
  "kubejs:schematic_industrial_anchor",
  "kubejs:schematic_isotopic_core",
  "kubejs:schematic_kinetic_frame",
  "kubejs:schematic_lattice_matrix",
  "kubejs:undercurrent_stabilizer",
  "kubejs:undercurrent_stabilizer_precursor",
  "laserio:laser_node",
  "malum:arcana_pylon",
  "malum:encyclopedia_arcana",
  "malum:soul_stained_steel_ingot",
  "malum:spirit_altar",
  "malum:spirit_crucible",
  "malum:spirit_jar",
  "mekanism:alloy_atomic",
  "mekanism:alloy_infused",
  "mekanism:alloy_reinforced",
  "mekanism:antiprotonic_nucleosynthesizer",
  "mekanism:basic_bin",
  "mekanism:basic_energy_cube",
  "mekanism:basic_purifying_factory",
  "mekanism:basic_universal_cable",
  "mekanism:block_osmium",
  "mekanism:chemical_injection_chamber",
  "mekanism:configurator",
  "mekanism:creative_energy_cube",
  "mekanism:crusher",
  "mekanism:digital_miner",
  "mekanism:dosimeter",
  "mekanism:electrolytic_separator",
  "mekanism:energized_smelter",
  "mekanism:enrichment_chamber",
  "mekanism:formulaic_assemblicator",
  "mekanism:geiger_counter",
  "mekanism:hazmat_boots",
  "mekanism:hazmat_gown",
  "mekanism:hazmat_mask",
  "mekanism:hazmat_pants",
  "mekanism:induction_casing",
  "mekanism:ingot_osmium",
  "mekanism:isotopic_centrifuge",
  "mekanism:metallurgic_infuser",
  "mekanism:pellet_antimatter",
  "mekanism:pellet_plutonium",
  "mekanism:pellet_polonium",
  "mekanism:purification_chamber",
  "mekanism:radioactive_waste_barrel",
  "mekanism:sps_casing",
  "mekanism:steel_casing",
  "mekanism:sulfuric_acid_bucket",
  "mekanismgenerators:fission_fuel_assembly",
  "mekanismgenerators:fission_reactor_logic_adapter",
  "mekanismgenerators:fusion_reactor_controller",
  "mekanismgenerators:heat_generator",
  "mekanismgenerators:saturating_condenser",
  "mekanismgenerators:turbine_casing",
  "mekanismgenerators:turbine_vent",
  "minecraft:blast_furnace",
  "minecraft:bread",
  "minecraft:chiseled_tuff_bricks",
  "minecraft:coal",
  "minecraft:copper_ingot",
  "minecraft:crafting_table",
  "minecraft:diamond",
  "minecraft:echo_shard",
  "minecraft:enchanted_golden_apple",
  "minecraft:experience_bottle",
  "minecraft:golden_apple",
  "minecraft:iron_block",
  "minecraft:iron_ingot",
  "minecraft:netherite_ingot",
  "minecraft:netherite_scrap",
  "minecraft:netherrack",
  "minecraft:oak_planks",
  "minecraft:recovery_compass",
  "minecraft:redstone",
  "minecraft:redstone_block",
  "minecraft:stone_pickaxe",
  "minecraft:torch",
  "modern_industrialization:analog_circuit",
  "modern_industrialization:assembler",
  "modern_industrialization:basic_machine_hull",
  "modern_industrialization:bronze_boiler",
  "modern_industrialization:bronze_ingot",
  "modern_industrialization:bronze_machine_casing",
  "modern_industrialization:chemical_reactor",
  "modern_industrialization:crude_oil_bucket",
  "modern_industrialization:digital_circuit",
  "modern_industrialization:distillation_tower",
  "modern_industrialization:distillery",
  "modern_industrialization:electric_macerator",
  "modern_industrialization:electric_wiremill",
  "modern_industrialization:electronic_circuit",
  "modern_industrialization:forge_hammer",
  "modern_industrialization:implosion_compressor",
  "modern_industrialization:iridium_ingot",
  "modern_industrialization:le_uranium_fuel_rod_quad",
  "modern_industrialization:lv_steam_turbine",
  "modern_industrialization:lv_storage_unit",
  "modern_industrialization:nuclear_casing",
  "modern_industrialization:nuclear_reactor",
  "modern_industrialization:oil_drilling_rig",
  "modern_industrialization:plutonium_ingot",
  "modern_industrialization:polyethylene_bucket",
  "modern_industrialization:quantum_barrel",
  "modern_industrialization:quantum_circuit",
  "modern_industrialization:quantum_machine_hull",
  "modern_industrialization:quantum_tank",
  "modern_industrialization:quantum_upgrade",
  "modern_industrialization:singularity",
  "modern_industrialization:stainless_steel_ingot",
  "modern_industrialization:steam_mining_drill",
  "modern_industrialization:superconductor_ingot",
  "modern_industrialization:uranium_fuel_rod",
  "mowziesmobs:wrought_helmet",
  "occultism:chalk_white",
  "occultism:dictionary_of_spirits",
  "occultism:sacrificial_bowl",
  "occultism:spirit_attuned_gem",
  "occultism:stable_wormhole",
  "occultism:storage_controller",
  "occultism:storage_remote",
  "oritech:advanced_computing_engine",
  "oritech:assembler_block",
  "oritech:basic_generator_block",
  "oritech:centrifuge_block",
  "oritech:exo_jetpack",
  "oritech:foundry_block",
  "oritech:jetpack",
  "oritech:jetpack_elytra",
  "oritech:large_storage_block",
  "oritech:laser_arm_block",
  "oritech:machine_core_1",
  "oritech:machine_core_2",
  "oritech:prometheum_ingot",
  "oritech:pulverizer_block",
  "oritech:reactor_controller",
  "oritech:wrench",
  "patchouli:guide_book",
  "pipez:advanced_upgrade",
  "pipez:improved_upgrade",
  "pipez:item_pipe",
  "pneumaticcraft:air_compressor",
  "pneumaticcraft:etching_acid_bucket",
  "pneumaticcraft:ingot_iron_compressed",
  "pneumaticcraft:logistics_drone",
  "pneumaticcraft:plastic",
  "pneumaticcraft:pneumatic_wrench",
  "pneumaticcraft:pressure_chamber_wall",
  "pneumaticcraft:pressure_gauge",
  "pneumaticcraft:pressure_tube",
  "pneumaticcraft:printed_circuit_board",
  "pneumaticcraft:programmer",
  "pneumaticcraft:safety_tube_module",
  "powah:book",
  "powah:energizing_orb",
  "powah:energy_cable_basic",
  "powah:energy_cell_basic",
  "powah:energy_cell_nitro",
  "powah:reactor_basic",
  "powah:reactor_nitro",
  "powah:thermo_generator_basic",
  "powah:thermo_generator_starter",
  "sophisticatedbackpacks:backpack",
  "twilightforest:twilight_scepter",
  "undergarden:forgotten_ingot"
]

const AFTERLIGHT_QUEST_COMMODITY = {
  "changed_old_items": [
    {
      "item": "minecraft:bread",
      "tag": "c:foods/bread"
    },
    {
      "item": "minecraft:red_bed",
      "tag": "minecraft:beds"
    },
    {
      "item": "immersiveengineering:ingot_steel",
      "tag": "c:ingots/steel"
    },
    {
      "item": "immersiveengineering:ingot_steel",
      "tag": "c:ingots/steel"
    }
  ],
  "declaration_count": 5,
  "fixture_sha256": "52ca9efb512a97827c25494fb4070287709c50f968547b6a1d0d33f2d855af27",
  "records": [
    "TAG c:foods/bread minecraft:bread,pneumaticcraft:sourdough_bread",
    "PRODUCER c:foods/bread minecraft:bread OK",
    "PRODUCER c:foods/bread pneumaticcraft:sourdough_bread OK",
    "TAG minecraft:beds aether:skyroot_bed,minecraft:black_bed,minecraft:blue_bed,minecraft:brown_bed,minecraft:cyan_bed,minecraft:gray_bed,minecraft:green_bed,minecraft:light_blue_bed,minecraft:light_gray_bed,minecraft:lime_bed,minecraft:magenta_bed,minecraft:orange_bed,minecraft:pink_bed,minecraft:purple_bed,minecraft:red_bed,minecraft:white_bed,minecraft:yellow_bed",
    "PRODUCER minecraft:beds minecraft:red_bed OK",
    "PRODUCER minecraft:beds aether:skyroot_bed OK",
    "TAG c:ingots/steel immersiveengineering:ingot_steel,mekanism:ingot_steel,modern_industrialization:steel_ingot,oritech:biosteel_ingot,oritech:steel_ingot",
    "PRODUCER c:ingots/steel immersiveengineering:ingot_steel OK",
    "PRODUCER c:ingots/steel mekanism:ingot_steel OK",
    "PRODUCER c:ingots/steel modern_industrialization:steel_ingot OK",
    "PRODUCER c:ingots/steel oritech:biosteel_ingot OK",
    "PRODUCER c:ingots/steel oritech:steel_ingot OK"
  ],
  "tags": [
    {
      "id": "c:foods/bread",
      "members": [
        "minecraft:bread",
        "pneumaticcraft:sourdough_bread"
      ],
      "producers": [
        "minecraft:bread",
        "pneumaticcraft:sourdough_bread"
      ]
    },
    {
      "id": "minecraft:beds",
      "members": [
        "aether:skyroot_bed",
        "minecraft:black_bed",
        "minecraft:blue_bed",
        "minecraft:brown_bed",
        "minecraft:cyan_bed",
        "minecraft:gray_bed",
        "minecraft:green_bed",
        "minecraft:light_blue_bed",
        "minecraft:light_gray_bed",
        "minecraft:lime_bed",
        "minecraft:magenta_bed",
        "minecraft:orange_bed",
        "minecraft:pink_bed",
        "minecraft:purple_bed",
        "minecraft:red_bed",
        "minecraft:white_bed",
        "minecraft:yellow_bed"
      ],
      "producers": [
        "minecraft:red_bed",
        "aether:skyroot_bed"
      ]
    },
    {
      "id": "c:ingots/steel",
      "members": [
        "immersiveengineering:ingot_steel",
        "mekanism:ingot_steel",
        "modern_industrialization:steel_ingot",
        "oritech:biosteel_ingot",
        "oritech:steel_ingot"
      ],
      "producers": [
        "immersiveengineering:ingot_steel",
        "mekanism:ingot_steel",
        "modern_industrialization:steel_ingot",
        "oritech:biosteel_ingot",
        "oritech:steel_ingot"
      ]
    }
  ]
}

function afterlightCommodityMembers(tagId) {
  const itemIds = Ingredient.of('#' + tagId).itemIds.toArray()
  const members = []
  let itemId
  for (let memberIndex = 0; memberIndex < itemIds.length; memberIndex++) {
    itemId = String(itemIds[memberIndex])
    if (members.indexOf(itemId) < 0) members.push(itemId)
  }
  return members.sort()
}

ServerEvents.loaded(event => {
  const bootNonce = '__AFTERLIGHT_BOOT_NONCE__'
  const invalid = AFTERLIGHT_QUEST_ITEM_IDS.filter(id => !Item.exists(id))
  if (invalid.length > 0) {
    invalid.forEach(id => console.error(`[AFTERLIGHT QUEST ITEM AUDIT] INVALID ${id}`))
    console.error(`[AFTERLIGHT QUEST ITEM AUDIT] FAILED ${AFTERLIGHT_QUEST_ITEM_AUDIT_DIGEST} ${bootNonce}`)
    return
  }
  console.info(`[AFTERLIGHT QUEST ITEM AUDIT] OK ${AFTERLIGHT_QUEST_ITEM_AUDIT_DIGEST} ${AFTERLIGHT_QUEST_ITEM_IDS.length} ${bootNonce}`)
  let commodityFailure = null
  const resolvedTags = {}
  AFTERLIGHT_QUEST_COMMODITY.tags.forEach(spec => {
    if (commodityFailure !== null) return
    const members = afterlightCommodityMembers(spec.id)
    if (members.length < 2) { commodityFailure = `${spec.id} TAG_TOO_SMALL`; return }
    if (JSON.stringify(members) !== JSON.stringify(spec.members)) { commodityFailure = `${spec.id} TAG_MEMBERS_MISMATCH`; return }
    resolvedTags[spec.id] = members
    spec.producers.forEach(producer => {
      if (commodityFailure === null && members.indexOf(producer) < 0) commodityFailure = `${producer} PRODUCER_MISSING`
    })
  })
  AFTERLIGHT_QUEST_COMMODITY.changed_old_items.forEach(oldItem => {
    if (commodityFailure !== null) return
    const members = resolvedTags[oldItem.tag]
    if (members === undefined || members.indexOf(oldItem.item) < 0) commodityFailure = `${oldItem.item} OLD_ITEM_MISSING`
  })
  if (commodityFailure !== null) {
    console.error(`[AFTERLIGHT QUEST COMMODITY AUDIT] INVALID ${commodityFailure}`)
    console.error(`[AFTERLIGHT QUEST COMMODITY AUDIT] FAILED ${AFTERLIGHT_QUEST_COMMODITY_FIXTURE_SHA256} ${AFTERLIGHT_QUEST_ITEM_AUDIT_DIGEST} ${bootNonce}`)
    return
  }
  AFTERLIGHT_QUEST_COMMODITY.records.forEach(record => console.info(`[AFTERLIGHT QUEST COMMODITY AUDIT] ${record}`))
  console.info(`[AFTERLIGHT QUEST COMMODITY AUDIT] OK ${AFTERLIGHT_QUEST_COMMODITY_FIXTURE_SHA256} ${AFTERLIGHT_QUEST_ITEM_AUDIT_DIGEST} ${AFTERLIGHT_QUEST_COMMODITY.declaration_count} ${bootNonce}`)
})
